version: "3.8"

services:
  db:
    image: mysql:5.7.39
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "Sfagdfhe43f"
      MYSQL_DATABASE: "testtask"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    depends_on:
      - db
    ports:
      - 3000:3000
    expose:
      - 3000
